### ISSUE TITLE
Update People on Main Page

### ISSUE THREAD

**Issue by sunschong** [CyberSecurityClub/cyber-club#65]
Student advisors:
-remove Amy, Edison, Dylan, Elizabeth
-add Danny and Samantha

Club Admin:
-remove Ananda
-titles:
     -Kerrie - Chief of Operations
     -Sunshine and Jennifer - keep developer titles, remove other titles
     -Fred- Manager of Operations

Board of Advisors:
-add Elizabeth as CNIT Instructor. She is displayed before Olivia

**Comment by jekai** [comment]
Completed:
Student advisors:
-remove Amy, Edison, Dylan, Elizabeth
-add Danny and Samantha

Club Admin:
-remove Ananda
-titles:
-Kerrie - Chief of Operations
-Sunshine and Jennifer - keep developer titles, remove other titles
-Fred- Manager of Operations

Board of Advisors:
-add Elizabeth as CNIT Instructor. She is displayed before Olivia
