### ISSUE TITLE
Replace Meeting Info Section to "Join our Mailing List"

### ISSUE THREAD

**Issue by sunschong** [CyberSecurityClub/cyber-club#66]
-Replace picture above Meeting button to a text box containing a bulleted list:
      "Newsletter Highlights:
              -career opportunities
              -cyber competitions
              -cyber news
              -student resources
            and more..."

-Change Meeting button to mailchimp logo
-Use "Prospective Members" link in the button

**Comment by jekai** [comment]
Completed:
-Replace picture above Meeting button to a text box containing a bulleted list:
"Newsletter Highlights:
-career opportunities
-cyber competitions
-cyber news
-student resources and more..."
-Change Meeting button to mailchimp logo
-Use "Prospective Members" link in the button
