### ISSUE TITLE
Update Navigation Bar for All pages

### ISSUE THREAD

**Issue by sunschong** [CyberSecurityClub/cyber-club#67]
"Teams":
-remove all teams except Competition Team
-add "Cyber Camp Team" - will contain info about volunteers, advisors, guest speakers, and sponsors (more details soon)

"Projects:"
-remove FB CTF (Sunshine will let Danny know when it's unlinked)
-add Cyber Camp 2018

**Comment by jekai** [comment]
Completed:
-remove all teams except Competition Team
-remove FB CTF (Sunshine will let Danny know when it's unlinked)
-add Cyber Camp 2018

Waiting for details:
-add "Cyber Camp Team" - will contain info about volunteers, advisors, guest speakers, and sponsors (more details soon)
