### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by sunschong** [CyberSecurityClub/cyber-club#69]
-temporarily hide about section
-replace mission/mission statement (more details later)
-Remove FB CTF from "Projects" section
-add Cyber Camp 2018 under "Projects" 
-Change Cyber Camp 2019 photo to a group photo from Cyber Camp 2019
-Add a group photo from Cyber Camp 2018 to Cyber Camp 2018

**Comment by jekai** [comment]
Completed:
-temporarily hide about section
-Remove FB CTF from "Projects" section
-add Cyber Camp 2018 under "Projects"
-Change Cyber Camp 2019 photo to a group photo from Cyber Camp 2019
-Add a group photo from Cyber Camp 2018 to Cyber Camp 2018

Waiting for details:
-replace mission/mission statement (more details later)

**Comment by sunschong** [comment]
-Under Projects:
-Replace Facebook CTF block with Cyber Camp 2018. Change the photo to be a group photo of Cyber Camp 2018 and have it linked to Cyber Camp 2018 page
-Under Teams:
-Remove Server Club
